#!/usr/bin/env python3

from intelhex import IntelHex, HexRecordError
import sys

if len(sys.argv) < 3:
    sys.stderr.write(f'{sys.argv[0]} <output verilog hex file> [intel hex file] ...\n')
    sys.exit(-1)

o = open(sys.argv[1], "wt")
for ihex_file in sys.argv[2:]:
    try:
        h = IntelHex(ihex_file)
        print(f'Converting {ihex_file} to {sys.argv[1]}')

        for i in range(h.maxaddr()):
            o.write(f'{h[i]:02x}\n')
        # for s, e in h.segments():
        #     if s != 0:
        #         o.write(f'\n@ {s:x}\n')
        #     for i in range(s, e):
        #         o.write(f'{h[i]:02x}\n')
    except HexRecordError:
        print(f'Copying {ihex_file} to {sys.argv[1]}')
        i = open(ihex_file, 'rt')
        o.write(i.read())
